<a href="https://colab.research.google.com/github/SwethaBurra123/KNN-ALGORITHM-IN-ML/blob/main/KNN_FLOWER_DATASET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import scikit-learn dataset library
from sklearn import datasets

In [4]:

irisDataset = datasets.load_iris()
print(irisDataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print(irisDataset.target_names)

['setosa' 'versicolor' 'virginica']


In [6]:
type(irisDataset.target)

numpy.ndarray

In [7]:
print(irisDataset.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [8]:
type(irisDataset)

sklearn.utils.Bunch

In [9]:
print(irisDataset.target[0:5])

[0 0 0 0 0]


In [10]:
print(irisDataset.data.shape)

(150, 4)


In [11]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

In [12]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(irisDataset.data, irisDataset.target,test_size=0.3)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn2 = KNeighborsClassifier(n_neighbors=2)

In [21]:
#Train the model using the training sets
knn2.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [23]:
#Predict the response for test dataset
y_pred2 = knn2.predict(X_test) 

In [27]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))

Accuracy: 0.9555555555555556


In [28]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

In [29]:
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

In [30]:
#Train the model using the training sets
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [31]:
#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [32]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [33]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9777777777777777


In [34]:
#Create KNN Classifier
knn1 = KNeighborsClassifier(n_neighbors=7)

In [35]:
#Train the model using the training sets
knn1.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [36]:
#Predict the response for test dataset
y_pred1 = knn1.predict(X_test)

In [37]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [38]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred1))

Accuracy: 1.0
